/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package databasesystem_project;

import java.awt.Window;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Monster Huma H5 v4.1
 */
public class Add_Employee extends javax.swing.JPanel {

    /**
     * Creates new form Add_Employee_panel
     */
    public Add_Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttn_add_emp = new javax.swing.JButton();
        bttn_logout_ae = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_new_username = new javax.swing.JTextField();
        txt_new_phone = new javax.swing.JTextField();
        txt_new_full_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_new_password = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(460, 550));

        bttn_add_emp.setText("ADD");
        bttn_add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_add_empActionPerformed(evt);
            }
        });

        bttn_logout_ae.setText("Logout");
        bttn_logout_ae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_logout_aeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel2.setText("Employee Name");

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel3.setText("Phone Number ");

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel4.setText("User Name");

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel5.setText("ADD EMPLOYEE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_new_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(txt_new_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)
                            .addComponent(txt_new_username, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(bttn_add_emp)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttn_logout_ae)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bttn_logout_ae)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_new_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(txt_new_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(txt_new_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_new_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bttn_add_emp)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_add_empActionPerformed
        // TODO add your handling code here:
        String new_name = txt_new_full_name.getText();
        char[] char_password = txt_new_password.getPassword();
        String password = new String(char_password);
        String username = txt_new_username.getText();
        String phone = txt_new_phone.getText();
        
        if(username.isEmpty() || password.isEmpty() || username.isEmpty() || phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!");
            return;
        }
        
        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {
                String sql = "INSERT INTO Employee (emp_name, username, password, phone, role) VALUES (?,?,?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, new_name);
                pst.setString(2, username);
                pst.setString(3, password);
                pst.setString(4, phone);
                pst.setString(5, "Employee");
                
                int added = pst.executeUpdate();
                if(added > 0){
                    JOptionPane.showMessageDialog(this, "Employee added succesfully!");
                    txt_new_full_name.setText("");
                    txt_new_password.setText("");
                    txt_new_username.setText("");
                    txt_new_phone.setText("");
                }else{
                    JOptionPane.showMessageDialog(this, "Failed to add employee!");
                }
                
                pst.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }//GEN-LAST:event_bttn_add_empActionPerformed

    private void bttn_logout_aeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_logout_aeActionPerformed
        // TODO add your handling code here:
        Admin_Login admin_login = new Admin_Login();
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // Bulunduğu frame'i kapat
        }
        admin_login.setVisible(true);
    }//GEN-LAST:event_bttn_logout_aeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_add_emp;
    private javax.swing.JButton bttn_logout_ae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_new_full_name;
    private javax.swing.JPasswordField txt_new_password;
    private javax.swing.JTextField txt_new_phone;
    private javax.swing.JTextField txt_new_username;
    // End of variables declaration//GEN-END:variables
}
