/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package databasesystem_project;

import java.awt.Window;
import java.io.File;
import java.sql.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Monster Huma H5 v4.1
 */
public class Add_Product extends javax.swing.JPanel {
    String image_name = "";
    float sale_price = 0;
    float cost_price = 0;
    int unit_value = 0;

    /**
     * Creates new form Add_Product_panel
     */
    public Add_Product() {
        initComponents();
        loadCategories();
        loadUnits();
    }

    private void loadCategories() {
        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT category_name FROM Category";

            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cmbx_category.removeAll();

            while (rs.next()) {
                String category_name = rs.getString("category_name");
                cmbx_category.addItem(category_name);
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            System.out.println("Hata (loadCategories): " + e.getMessage());
        }
    }
    
    private void loadUnits(){
        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT unit_name FROM Unit";

            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            cmbx_unit_id.removeAll();

            while (rs.next()) {
                String unit_name = rs.getString("unit_name");
                cmbx_unit_id.addItem(unit_name);
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            System.out.println("Hata (loadCategories): " + e.getMessage());
        }
    }
    
    public int getCategoryId(String categoryName) {
        int id = -1;

        String sql = "SELECT category_id FROM category WHERE category_name = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, categoryName);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("category_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Category id bulundu:" +id);
        return id;
    }
    
    public int getUnitId(String unitName) {
        int id = -1;

        String sql = "SELECT unit_id FROM Unit WHERE unit_name = ?";
        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, unitName);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("unit_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Unit id bulundu:" +id);
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_sale_price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cost_price = new javax.swing.JTextField();
        bttn_add_ap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bttn_logout_ap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbx_category = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_product_name = new javax.swing.JTextField();
        bttn_choose_file = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbx_unit_id = new javax.swing.JComboBox<>();
        txt_unit_value = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(460, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel2.setText("Unit");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 99, -1));
        add(txt_sale_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 314, -1));

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel4.setText("Cost Price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 99, -1));
        add(txt_cost_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 314, -1));

        bttn_add_ap.setText("ADD");
        bttn_add_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_add_apActionPerformed(evt);
            }
        });
        add(bttn_add_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel5.setText("ADD PRODUCT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        bttn_logout_ap.setText("Logout");
        bttn_logout_ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_logout_apActionPerformed(evt);
            }
        });
        add(bttn_logout_ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel1.setText("Category");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        add(cmbx_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 314, -1));

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 81, -1));
        add(txt_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 314, -1));

        bttn_choose_file.setText("Choose a picture file");
        bttn_choose_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_choose_fileActionPerformed(evt);
            }
        });
        add(bttn_choose_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 310, -1));

        jLabel6.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel6.setText("Sale Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 99, -1));

        add(cmbx_unit_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, -1));
        add(txt_unit_value, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_logout_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_logout_apActionPerformed
        // TODO add your handling code here:
        Admin_Login admin_login = new Admin_Login();
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // Bulunduğu frame'i kapat
        }
        admin_login.setVisible(true);
    }//GEN-LAST:event_bttn_logout_apActionPerformed

    private void bttn_choose_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_choose_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser file_chooser = new JFileChooser(new File("C:\\Users\\Monster Huma H5 v4.1\\Desktop\\SQL Project\\DatabaseSystem_Project\\src\\databasesystem_project\\products"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "png");
        file_chooser.setFileFilter(filter);

        int result = file_chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file_chooser.getSelectedFile();
            image_name = selectedFile.getName();
            bttn_choose_file.setText(image_name);
        }
    }//GEN-LAST:event_bttn_choose_fileActionPerformed

    private void bttn_add_apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_add_apActionPerformed
        // TODO add your handling code here:
        String category = (String) cmbx_category.getSelectedItem();
        String name = txt_product_name.getText();
        unit_value = Integer.parseInt(txt_unit_value.getText());
        String unit_name = (String) cmbx_unit_id.getSelectedItem();
        sale_price = Float.parseFloat(txt_sale_price.getText());
        cost_price = Float.parseFloat(txt_cost_price.getText());

        if (category.isEmpty() || name.isEmpty() || sale_price == 0 || cost_price == 0 || unit_value == 0 || unit_name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all the fields!");
            return;
        }
        if (image_name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a image for product!");
            return;
        }

        int decision = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this product?");
        if(decision == JOptionPane.YES_OPTION){
            try {
                Connection conn = DBConnection.getConnection();
                if (conn != null) {
                    String sql = "INSERT INTO Product (category_id, product_name, cost_price, sale_price, unit_id, unit_value, image_path) VALUES (?,?,?,?,?,?,?)";
                    PreparedStatement pst = conn.prepareStatement(sql);
                    pst.setInt(1, getCategoryId(category));
                    pst.setString(2, name);
                    pst.setFloat(3, cost_price);
                    pst.setFloat(4, sale_price);
                    pst.setInt(5, getUnitId(unit_name));
                    pst.setInt(6, unit_value);
                    pst.setString(7, image_name);

                    int added = pst.executeUpdate();
                    if (added > 0) {
                        JOptionPane.showMessageDialog(this, "Product added succesfully!");
                        txt_product_name.setText("");
                        txt_cost_price.setText("");
                        txt_sale_price.setText("");
                        txt_unit_value.setText("");
                        cmbx_unit_id.setSelectedItem("");
                        cmbx_category.setSelectedItem("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed to add product!");
                    }

                    pst.close();
                    conn.close();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
            }
        }else{
            return;
        }
    }//GEN-LAST:event_bttn_add_apActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_add_ap;
    private javax.swing.JButton bttn_choose_file;
    private javax.swing.JButton bttn_logout_ap;
    private javax.swing.JComboBox<String> cmbx_category;
    private javax.swing.JComboBox<String> cmbx_unit_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_cost_price;
    private javax.swing.JTextField txt_product_name;
    private javax.swing.JTextField txt_sale_price;
    private javax.swing.JTextField txt_unit_value;
    // End of variables declaration//GEN-END:variables
}
