/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

import java.sql.*;
import java.util.ArrayList;
import java.awt.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imans
 */
public class Make_Order extends javax.swing.JFrame {

    String user_name;
    DefaultTableModel main_model = new DefaultTableModel();

    /**
     * Creates new form Make_Order
     */
    public Make_Order(String name) {
        initComponents();
        main_model.setColumnIdentifiers(new Object[]{
            "Product Name",
            "Quantity",
            "Unit Price",
            "Total Price"
        });
        this.user_name = name;
    }
    
    public Make_Order(DefaultTableModel model) {
        initComponents();
        /*main_model.setColumnIdentifiers(new Object[]{
            "Product Name",
            "Quantity",
            "Unit Price",
            "Total Price"
        });*/
        main_model = model;
    }

    public int getCategoryId(String categoryName) {
        int id = -1;

        String sql = "SELECT category_id FROM category WHERE category_name = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, categoryName);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("category_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Category id bulundu:" + id);
        return id;
    }

    public ArrayList<Product> getProducts(int categoryId) {
        System.out.println("ürünleri listeye eklemek için metoda girildi.");
        ArrayList<Product> list = new ArrayList<>();

        String sql = "SELECT product_name, sale_Price ,image_path FROM product WHERE category_id = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, categoryId);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                String productName = rs.getString("product_name");
                float sale_price = rs.getFloat("sale_price");
                String productPath = rs.getString("image_path");

                list.add(new Product(productName, sale_price, productPath));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Product list: ");
        for (Product pro : list) {
            System.out.println("-> " + pro.getName());
        }
        return list;
    }

    public void loadCategory(String categoryName) {
        System.out.println("ürünler eklenmek için işlem başladı");
        // grid paneli temizle
        grid_panel.removeAll();

        grid_panel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));

        // category id al
        System.out.println("kategory id hesaplanıyor...");
        int categoryId = getCategoryId(categoryName);
        if (categoryId == -1) {
            System.out.println("Category not found: " + categoryName);
            return;
        }

        // ürün listesi çek
        System.out.println("ürünler listeye eklenecek...");
        ArrayList<Product> products = getProducts(categoryId);

        // ürünleri grid içine ekle
        System.out.println("ürünler panel olarak oluşturulup eklenecek...");
        for (Product p : products) {
            ItemPanel item = new ItemPanel(p, main_model);
            grid_panel.add(item);
        }

        // yenile
        grid_panel.revalidate();
        grid_panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        bttn_okay = new javax.swing.JButton();
        bttn_menu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_food = new javax.swing.JMenu();
        menu_cold_drink = new javax.swing.JMenu();
        menu_hot_drink = new javax.swing.JMenu();
        menu_fastfood = new javax.swing.JMenu();
        menu_sweets = new javax.swing.JMenu();
        menu_snacks = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bttn_okay.setText("Okay");
        bttn_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_okayActionPerformed(evt);
            }
        });

        bttn_menu.setText("Menu");
        bttn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttn_menu)
                .addGap(31, 31, 31)
                .addComponent(bttn_okay)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_okay)
                    .addComponent(bttn_menu))
                .addContainerGap())
        );

        grid_panel.setBackground(new java.awt.Color(255, 255, 204));
        grid_panel.setPreferredSize(new java.awt.Dimension(780, 514));
        grid_panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\imans\\OneDrive\\Masaüstü\\loginform_0.jpg")); // NOI18N
        grid_panel.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 2, 18)); // NOI18N
        jLabel2.setText("A team that serves with care, quality, and passion");
        grid_panel.add(jLabel2);

        jScrollPane1.setViewportView(grid_panel);

        menu_food.setText("Food");
        menu_food.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_foodMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_food);

        menu_cold_drink.setText("Cold Drink");
        menu_cold_drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_cold_drinkMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_cold_drink);

        menu_hot_drink.setText("Hot Drink");
        menu_hot_drink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_hot_drinkMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_hot_drink);

        menu_fastfood.setText("Fast Food");
        menu_fastfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_fastfoodMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_fastfood);

        menu_sweets.setText("Sweets");
        menu_sweets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sweetsMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sweets);

        menu_snacks.setBackground(new java.awt.Color(255, 255, 204));
        menu_snacks.setText("Snacks");
        menu_snacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_snacksMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_snacks);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(user_name);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_bttn_menuActionPerformed

    private void menu_snacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_snacksMouseClicked
        // TODO add your handling code here:
        loadCategory("Snacks");
    }//GEN-LAST:event_menu_snacksMouseClicked

    private void menu_sweetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sweetsMouseClicked
        // TODO add your handling code here:
        loadCategory("Sweets");
    }//GEN-LAST:event_menu_sweetsMouseClicked

    private void menu_fastfoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_fastfoodMouseClicked
        // TODO add your handling code here:
        loadCategory("Fast Food");
    }//GEN-LAST:event_menu_fastfoodMouseClicked

    private void menu_hot_drinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_hot_drinkMouseClicked
        // TODO add your handling code here:
        loadCategory("Hot Drink");
    }//GEN-LAST:event_menu_hot_drinkMouseClicked

    private void menu_cold_drinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_cold_drinkMouseClicked
        // TODO add your handling code here:
        loadCategory("Cold Drink");
    }//GEN-LAST:event_menu_cold_drinkMouseClicked

    private void menu_foodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_foodMouseClicked
        // TODO add your handling code here:
        loadCategory("Food");
    }//GEN-LAST:event_menu_foodMouseClicked

    private void bttn_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_okayActionPerformed
        // TODO add your handling code here:
        Order_Detail orders = new Order_Detail(main_model);
        this.dispose();
        orders.setVisible(true);
    }//GEN-LAST:event_bttn_okayActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Make_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Make_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Make_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Make_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Make_Order().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_menu;
    private javax.swing.JButton bttn_okay;
    private javax.swing.JPanel grid_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_cold_drink;
    private javax.swing.JMenu menu_fastfood;
    private javax.swing.JMenu menu_food;
    private javax.swing.JMenu menu_hot_drink;
    private javax.swing.JMenu menu_snacks;
    private javax.swing.JMenu menu_sweets;
    // End of variables declaration//GEN-END:variables
}
