/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

import java.awt.CardLayout;

/**
 *
 * @author imans
 */
public class Manage extends javax.swing.JFrame {
    CardLayout cardlayout;
    /**
     * Creates new form Manage
     */
    public Manage() {
        initComponents();
        
        cardlayout = (CardLayout) main_panel.getLayout();
        
        Add_Product add_product = new Add_Product();
        Remove_Product rmv_product = new Remove_Product();
        Add_Employee add_employee = new Add_Employee();
        Remove_Employee rmv_employee = new Remove_Employee();
        
        
        main_panel.add(add_product, "add_product");
        main_panel.add(add_employee, "add_employee");
        main_panel.add(rmv_product, "rmv_product");
        main_panel.add(rmv_employee, "rmv_employee");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_add_product = new javax.swing.JMenuItem();
        menu_rmv_product = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_add_employee = new javax.swing.JMenuItem();
        menu_rmv_employee = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 204));
        main_panel.setForeground(new java.awt.Color(204, 204, 255));
        main_panel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("jLabel1");
        main_panel.add(jLabel1, "card2");

        jMenu1.setText("Product");

        menu_add_product.setText("Add product");
        menu_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_productActionPerformed(evt);
            }
        });
        jMenu1.add(menu_add_product);

        menu_rmv_product.setText("Remove Product");
        menu_rmv_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rmv_productActionPerformed(evt);
            }
        });
        jMenu1.add(menu_rmv_product);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Employee");

        menu_add_employee.setText("Add employee");
        menu_add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_employeeActionPerformed(evt);
            }
        });
        jMenu2.add(menu_add_employee);

        menu_rmv_employee.setText("Rmove employee");
        menu_rmv_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_rmv_employeeActionPerformed(evt);
            }
        });
        jMenu2.add(menu_rmv_employee);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_productActionPerformed
        // TODO add your handling code here:
        cardlayout.show(main_panel, "add_product");
    }//GEN-LAST:event_menu_add_productActionPerformed

    private void menu_rmv_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rmv_employeeActionPerformed
        // TODO add your handling code here:
        cardlayout.show(main_panel, "rmv_employee");
    }//GEN-LAST:event_menu_rmv_employeeActionPerformed

    private void menu_add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_employeeActionPerformed
        // TODO add your handling code here:
        cardlayout.show(main_panel, "add_employee");
    }//GEN-LAST:event_menu_add_employeeActionPerformed

    private void menu_rmv_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_rmv_productActionPerformed
        // TODO add your handling code here:
        cardlayout.show(main_panel, "rmv_product");
    }//GEN-LAST:event_menu_rmv_productActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JMenuItem menu_add_employee;
    private javax.swing.JMenuItem menu_add_product;
    private javax.swing.JMenuItem menu_rmv_employee;
    private javax.swing.JMenuItem menu_rmv_product;
    // End of variables declaration//GEN-END:variables
}
