/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

/**
 *
 * @author imans
 */
public class Menu extends javax.swing.JFrame {
    String user_name;
    /**
     * Creates new form Menu
     */
    public Menu(String name) {
        initComponents();
        this.user_name = name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bttn_menu_purches = new javax.swing.JButton();
        bttn_menu_salesitem = new javax.swing.JButton();
        bttn_menu_reorder = new javax.swing.JButton();
        bttn_menu_stock = new javax.swing.JButton();
        bttn_menu_makeorder = new javax.swing.JButton();
        bttn_logout_menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        bttn_menu_purches.setText("Purches");
        bttn_menu_purches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menu_purchesActionPerformed(evt);
            }
        });

        bttn_menu_salesitem.setText("Sales Item ");
        bttn_menu_salesitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menu_salesitemActionPerformed(evt);
            }
        });

        bttn_menu_reorder.setText("Reorder");
        bttn_menu_reorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menu_reorderActionPerformed(evt);
            }
        });

        bttn_menu_stock.setText("Stock");
        bttn_menu_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menu_stockActionPerformed(evt);
            }
        });

        bttn_menu_makeorder.setText("Make Order");
        bttn_menu_makeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menu_makeorderActionPerformed(evt);
            }
        });

        bttn_logout_menu.setText("Log Out");
        bttn_logout_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_logout_menuActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\imans\\OneDrive\\Masaüstü\\WhatsApp Görsel 2025-12-15 saat 23.30.15_10f42b52.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttn_logout_menu)
                .addGap(49, 49, 49))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(bttn_menu_makeorder)
                        .addGap(51, 51, 51)
                        .addComponent(bttn_menu_reorder)
                        .addGap(70, 70, 70)
                        .addComponent(bttn_menu_salesitem)
                        .addGap(80, 80, 80)
                        .addComponent(bttn_menu_stock)
                        .addGap(84, 84, 84)
                        .addComponent(bttn_menu_purches))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_menu_makeorder)
                    .addComponent(bttn_menu_reorder)
                    .addComponent(bttn_menu_salesitem)
                    .addComponent(bttn_menu_stock)
                    .addComponent(bttn_menu_purches))
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(bttn_logout_menu)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_menu_purchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menu_purchesActionPerformed
        // TODO add your handling code here:
        Purches purchase = new Purches(user_name);
        this.dispose();
        purchase.setVisible(true);
    }//GEN-LAST:event_bttn_menu_purchesActionPerformed

    private void bttn_menu_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menu_stockActionPerformed
        // TODO add your handling code here:
        Stock stock = new Stock(user_name);
        this.dispose();
        stock.setVisible(true);
    }//GEN-LAST:event_bttn_menu_stockActionPerformed

    private void bttn_menu_makeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menu_makeorderActionPerformed
        // TODO add your handling code here:
        Make_Order make_order = new Make_Order(user_name);
        this.dispose();
        make_order.setVisible(true);
    }//GEN-LAST:event_bttn_menu_makeorderActionPerformed

    private void bttn_menu_reorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menu_reorderActionPerformed
        // TODO add your handling code here:
        Reorder reorder = new Reorder(user_name);
        this.dispose();
        reorder.setVisible(true);
    }//GEN-LAST:event_bttn_menu_reorderActionPerformed

    private void bttn_menu_salesitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menu_salesitemActionPerformed
        // TODO add your handling code here:
        Sales_Item salesitem = new Sales_Item(user_name);
        this.dispose();
        salesitem.setVisible(true);
    }//GEN-LAST:event_bttn_menu_salesitemActionPerformed

    private void bttn_logout_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_logout_menuActionPerformed
        // TODO add your handling code here:
        Employee_Login emp_login = new Employee_Login();
        this.dispose();
        emp_login.setVisible(true);
    }//GEN-LAST:event_bttn_logout_menuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_logout_menu;
    private javax.swing.JButton bttn_menu_makeorder;
    private javax.swing.JButton bttn_menu_purches;
    private javax.swing.JButton bttn_menu_reorder;
    private javax.swing.JButton bttn_menu_salesitem;
    private javax.swing.JButton bttn_menu_stock;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
