/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

import java.awt.*;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imans
 */
public class Payment_Type extends javax.swing.JFrame {

    DefaultTableModel model;
    float total;
    float disc_total = total;

    /**
     * Creates new form Payment_Type
     */
    public Payment_Type(float total, DefaultTableModel model) {
        initComponents();
        this.model = model;
        this.total = total;
        lbl_total.setText(String.valueOf(total));
    }

    public int getProductId(String productName) {
        int id = -1;

        String sql = "SELECT product_id FROM Product WHERE product_name = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, productName);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("product_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Product id bulundu:" + id);
        return id;
    }

    private void stockReduction(int product_id, int count) {
        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {
                String sql = "UPDATE Stock SET quantity = quantity - ? WHERE product_id = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, count);
                pst.setInt(2, product_id);

                pst.executeUpdate();

                pst.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }

    private void addSalesItems(DefaultTableModel model, int salesId) {
        String sql = "INSERT INTO SalesItems (sales_id, product_id, quantity, unit_price) VALUES (?,?,?,?)";

        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {

                PreparedStatement pst = conn.prepareStatement(sql);
                for (int i = 0; i < model.getRowCount(); i++) {
                    String product_name = model.getValueAt(i, 0).toString();
                    int quantity = Integer.parseInt(model.getValueAt(i, 1).toString());
                    float unit_price = Float.parseFloat(model.getValueAt(i, 2).toString());
                    pst.setInt(1, salesId);
                    pst.setInt(2, getProductId(product_name));
                    pst.setFloat(3, quantity);
                    pst.setFloat(4, unit_price);

                    pst.executeUpdate();
                    stockReduction(getProductId(product_name), quantity);
                }

                JOptionPane.showMessageDialog(this, "Shopping completed succesfully!!");
                pst.close();
                conn.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttn_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbttn_credit_card = new javax.swing.JRadioButton();
        rbttn_cash = new javax.swing.JRadioButton();
        bttn_complete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_total_for_discount = new javax.swing.JLabel();
        bttn_menu = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chck_box_discount = new javax.swing.JCheckBox();
        txt_discount = new javax.swing.JTextField();
        lbl_valid_invalid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        bttn_group.add(rbttn_credit_card);
        rbttn_credit_card.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rbttn_credit_card.setText("credit card");

        bttn_group.add(rbttn_cash);
        rbttn_cash.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        rbttn_cash.setText("cash");
        rbttn_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbttn_cashActionPerformed(evt);
            }
        });

        bttn_complete.setText("Complete");
        bttn_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_completeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel2.setText("TOTAL:");

        lbl_total_for_discount.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N

        bttn_menu.setText("Menu");
        bttn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menuActionPerformed(evt);
            }
        });

        lbl_total.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lbl_total.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel3.setText("Please select payment type !");

        chck_box_discount.setFont(new java.awt.Font("Imprint MT Shadow", 2, 18)); // NOI18N
        chck_box_discount.setText(" Enter a discount code:");
        chck_box_discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chck_box_discountActionPerformed(evt);
            }
        });

        txt_discount.setEnabled(false);
        txt_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_discountKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_total_for_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chck_box_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_valid_invalid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_discount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbttn_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bttn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(bttn_complete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(rbttn_credit_card, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(chck_box_discount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_valid_invalid, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_total_for_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbttn_cash)
                    .addComponent(rbttn_credit_card))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn_complete)
                    .addComponent(bttn_menu))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_completeActionPerformed
        // TODO add your handling code here:
        if (!rbttn_cash.isSelected() && !rbttn_credit_card.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please choose a payment type!");
            return;
        }

        LocalDate date = LocalDate.now();
        Date today = Date.valueOf(date);
        int type = rbttn_cash.isSelected() ? 1 : 2;
        float total_price = disc_total;
        System.out.println("******** in complete button, total_price: " +total_price+ " *******");

        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {
                String sql = "INSERT INTO Sales (sale_date, total_amount, payment_id) VALUES (?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                pst.setDate(1, today);
                pst.setFloat(2, total_price);
                pst.setInt(3, type);

                pst.executeUpdate();

                int salesId = -1;
                ResultSet rs = pst.getGeneratedKeys();
                if (rs.next()) {
                    salesId = rs.getInt(1);
                }

                addSalesItems(model, salesId);
                JOptionPane.showMessageDialog(this, "Shopping completed succesfully!!");

                rs.close();
                pst.close();
                conn.close();
                model.setRowCount(0);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage());
        }

    }//GEN-LAST:event_bttn_completeActionPerformed

    private void bttn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menuActionPerformed
        // TODO add your handling code here:

        Make_Order make_order = new Make_Order(model);
        this.dispose();
        make_order.setVisible(true);
    }//GEN-LAST:event_bttn_menuActionPerformed

    private void chck_box_discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chck_box_discountActionPerformed
        // TODO add your handling code here:
        if (chck_box_discount.isSelected()) {
            txt_discount.setEnabled(true);
        } else {
            txt_discount.setEnabled(false);
        }
    }//GEN-LAST:event_chck_box_discountActionPerformed

    private void txt_discountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_discountKeyReleased
        // TODO add your handling code here:
        String discount_code = txt_discount.getText();

        String sql = "SELECT discount_rate, start_date, end_date FROM Discount WHERE code = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, discount_code);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                LocalDate today = LocalDate.now();
                LocalDate start_date = rs.getDate("start_date").toLocalDate();
                LocalDate end_date = rs.getDate("end_date").toLocalDate();
                float discount_rate = rs.getFloat("discount_rate");
                lbl_valid_invalid.setText("");

                if (today.isAfter(start_date) && today.isBefore(end_date)) {
                    lbl_total.setFont(new Font("Imprint MT Shadow", Font.ITALIC, 12));
                    lbl_total.setForeground(new Color(0, 0, 0, 128));
                    disc_total = total - (total / 100 * discount_rate);
                    lbl_total_for_discount.setText(String.valueOf(disc_total));
                } else {
                    lbl_valid_invalid.setText("Historical Past Code!");
                }
            } else {
                lbl_valid_invalid.setText("Invalid code!");
                lbl_total_for_discount.setText("");
                lbl_total.setText(String.valueOf(total));
                lbl_total.setFont(new Font("Imprint MT Shadow", Font.BOLD, 18));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_discountKeyReleased

    private void rbttn_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbttn_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbttn_cashActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Payment_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Payment_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Payment_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Payment_Type.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Payment_Type().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_complete;
    private javax.swing.ButtonGroup bttn_group;
    private javax.swing.JButton bttn_menu;
    private javax.swing.JCheckBox chck_box_discount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_total_for_discount;
    private javax.swing.JLabel lbl_valid_invalid;
    private javax.swing.JRadioButton rbttn_cash;
    private javax.swing.JRadioButton rbttn_credit_card;
    private javax.swing.JTextField txt_discount;
    // End of variables declaration//GEN-END:variables
}
