/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author imans
 */
public class Purches extends javax.swing.JFrame {

    String user_name;

    private Integer currentOrderId = null;
    private int loggedEmployedId;

    /**
     * Creates new form Purches
     */
    public Purches(String name) {
        initComponents();
        this.user_name = name;
        this.loggedEmployedId = getEmployeeId(user_name);

       loadFoodProducts();   // jComboBox1
        loadProducts();       // jComboBox2

        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Product Name", "supplier Name", "Quantity", "Unit Price", "Total"}, 0
        );
        jTable1.setModel(model);
    }

    private void loadFoodProducts() {
        try (Connection con = DBConnection.getConnection(); PreparedStatement pst = con.prepareStatement(
                "SELECT ingredients FROM FoodProduct"); ResultSet rs = pst.executeQuery()) {

            jComboBox1.removeAllItems();
            jComboBox1.addItem("-- Select Food --");

            while (rs.next()) {
                jComboBox1.addItem(rs.getString("ingredients"));
            }

        } catch (Exception e) {
            System.out.println("loadFoodProducts: " + e.getMessage());
        }
    }

    private void loadProducts() {
        try (Connection con = DBConnection.getConnection(); PreparedStatement pst = con.prepareStatement(
                "SELECT product_name FROM Product ORDER BY product_name"); ResultSet rs = pst.executeQuery()) {

            jComboBox2.removeAllItems();
            jComboBox2.addItem("-- Select Product --");

            while (rs.next()) {
                jComboBox2.addItem(rs.getString("product_name"));
            }

        } catch (Exception e) {
            System.out.println("loadProducts: " + e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bttn_menu = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        jLabel3.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel3.setText("STOCK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pasta", "mushroom", "cream", "cheese", "mantı", "yogurt", "butter", "tomato paste", "salt", "lentils", "tomato", "potato", "meatballs", "sour cherries", "spinach", "pine nuts", "oil" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Didi Ice Tea Lemon 330ml", "Fuse Tea Peach 330ml", "Camlıca Gazoz 330ml", "Yedigün Portakal 330ml", "Pınar Water 500ml", "Türk Cayı (Hot Tea Cup)", "Türk Kahvesi", "Salep Cup", "Tost Peynirli", "Tavuk Döner Dürüm", "Simit", "Patates Kızartması Mini", "Ulker Cikolata 60g", "Eti Browni Gold Cake", "şölen Ozmo Cikolata", "Eti Crax 50g", "Torku Banada Mini", "Ulker Krispi 50g", "Eti Tutku Biscuit", "Torku Cokomio Bar" }));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel1.setText("food_product");

        jLabel2.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jLabel2.setText("product");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "Supplier Name", "Quantity", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        jButton1.setText("Complete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel4.setText("PURCHES ORDER");

        bttn_menu.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        bttn_menu.setText("Menu");
        bttn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(bttn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel4)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(bttn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(user_name);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_bttn_menuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String foodName = jComboBox1.getSelectedItem().toString();
        String productName = jComboBox2.getSelectedItem().toString();

        boolean foodChosen = !foodName.equals("-- Select Food --");
        boolean productChosen = !productName.equals("-- Select Product --");

        int foodQty = (int) jSpinner2.getValue();   // ✅ Food spinner
        int productQty = (int) jSpinner1.getValue(); // ✅ Product spinner

        if (!foodChosen && !productChosen) {
            JOptionPane.showMessageDialog(this, "Select Food or Product (or both).");
            return;
        }

        if (foodChosen && foodQty <= 0) {
            JOptionPane.showMessageDialog(this, "Food quantity must be greater than 0.");
            return;
        }

        if (productChosen && productQty <= 0) {
            JOptionPane.showMessageDialog(this, "Product quantity must be greater than 0.");
            return;
        }

        try (Connection con = DBConnection.getConnection()) {

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            // =========================
            // 🍝 FOOD PRODUCT
            if (foodChosen) {

                String supplierName = "";
                double foodPrice = 0;

                PreparedStatement pstFood = con.prepareStatement(
                        "SELECT s.supplier_name, f.cost_price "
                        + "FROM FoodProduct f "
                        + "JOIN Supplier s ON f.supplier_id = s.supplier_id "
                        + "WHERE f.ingredients = ?"
                );

                pstFood.setString(1, foodName);

                ResultSet rsFood = pstFood.executeQuery();
                if (rsFood.next()) {
                    supplierName = rsFood.getString("supplier_name");
                    foodPrice = rsFood.getDouble("cost_price"); // ✅ الآن صحيح
                }

                rsFood.close();
                pstFood.close();

                model.addRow(new Object[]{
                    foodName,
                    supplierName,
                    foodQty,
                    foodPrice,
                    foodQty * foodPrice
                });
            }

            // =========================
            // 🥤 NORMAL PRODUCT
            // =========================
            if (productChosen) {

                int productId = 0;
                double unitPrice = 0;
                String supplierName = "";

                PreparedStatement pst = con.prepareStatement(
                        "SELECT p.product_id, p.cost_price, s.supplier_name "
                        + "FROM Product p "
                        + "JOIN Supplier s ON p.supplier_id = s.supplier_id "
                        + "WHERE p.product_name = ?"
                );
                pst.setString(1, productName);

                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    productId = rs.getInt("product_id");
                    unitPrice = rs.getDouble("cost_price");
                    supplierName = rs.getString("supplier_name");
                }

                rs.close();
                pst.close();

                model.addRow(new Object[]{
                    productName,
                    supplierName,
                    productQty,
                    unitPrice,
                    productQty * unitPrice
                });
            }

            // 🔄 reset spinners
            jSpinner1.setValue(0);
            jSpinner2.setValue(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
// 🔄 Reset ComboBoxes to first option
        jComboBox1.setSelectedIndex(0); // -- Select Food --
        jComboBox2.setSelectedIndex(0); // -- Select Product --

// 🔄 Reset Spinners
        jSpinner1.setValue(0); // Product quantity
        jSpinner2.setValue(0); // Food quantity


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No items to complete order.");
            return;
        }

        try (Connection con = DBConnection.getConnection()) {

            con.setAutoCommit(false);

            // 1) INSERT INTO PurchaseOrder
            PreparedStatement pstOrder = con.prepareStatement(
                    "INSERT INTO PurchaseOrder (order_date, status, created_by) "
                    + "VALUES (GETDATE(), 'Completed', ?)",
                    Statement.RETURN_GENERATED_KEYS
            );

            pstOrder.setInt(1, loggedEmployedId);
            pstOrder.executeUpdate();

            ResultSet rsKey = pstOrder.getGeneratedKeys();
            int orderId = 0;
            if (rsKey.next()) {
                orderId = rsKey.getInt(1);
            }
            rsKey.close();
            pstOrder.close();

            if (orderId == 0) {
                con.rollback();
                JOptionPane.showMessageDialog(this, "Failed to create order!");
                return;
            }

            // 2) INSERT ITEMS
            PreparedStatement pstItem = con.prepareStatement(
                    "INSERT INTO PurchaseOrderItems "
                    + "(order_id, product_id, FoodProduct_id, supplier_id, quantity, unit_price) "
                    + "VALUES (?, ?, ?, ?, ?, ?)"
            );

            for (int i = 0; i < model.getRowCount(); i++) {

                String itemName = model.getValueAt(i, 0).toString();
                String supplierName = model.getValueAt(i, 1).toString();
                int quantity = Integer.parseInt(model.getValueAt(i, 2).toString());
                double unitPrice = Double.parseDouble(model.getValueAt(i, 3).toString());

                Integer productId = getProductIdByName(con, itemName);              // returns null if not found
                Integer foodId = getFoodProductIdByIngredient(con, itemName);       // returns null if not found
                int supplierId = getSupplierIdByName(con, supplierName);

                pstItem.setInt(1, orderId);

                // ✅ لازم واحد منهم فقط (Product أو FoodProduct)
                if (productId != null) {
                    pstItem.setInt(2, productId);
                    pstItem.setNull(3, java.sql.Types.INTEGER);
                } else if (foodId != null) {
                    pstItem.setNull(2, java.sql.Types.INTEGER);
                    pstItem.setInt(3, foodId);
                } else {
                    // لا موجود في Product ولا في FoodProduct
                    con.rollback();
                    JOptionPane.showMessageDialog(this, "Item not found in DB: " + itemName);
                    return;
                }

                pstItem.setInt(4, supplierId);
                pstItem.setInt(5, quantity);
                pstItem.setDouble(6, unitPrice);

                pstItem.addBatch();
            }

            pstItem.executeBatch();
            pstItem.close();

            con.commit();

            JOptionPane.showMessageDialog(
                    this,
                    "Order completed successfully!\nOrder ID: " + orderId
            );

            // Return to Menu
            Menu menu = new Menu(user_name);
            this.dispose();
            menu.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed
    private Integer getProductIdByName(Connection con, String productName) throws Exception {

        PreparedStatement pst = con.prepareStatement(
                "SELECT product_id FROM Product WHERE product_name = ?"
        );
        pst.setString(1, productName);

        ResultSet rs = pst.executeQuery();

        Integer id = null;
        if (rs.next()) {
            id = rs.getInt("product_id");
        }

        rs.close();
        pst.close();

        return id;  // null if not found
    }

   private int getEmployeeId(String employeeName) {
        int id = -1;

        String sql = "SELECT emp_id FROM Employee WHERE username = ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, employeeName);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                id = rs.getInt("emp_id");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Employee id bulundu:" + id);
        return id;
}
// ===================================
// 🔎 Get Supplier ID by Name
// ===================================

     private int getSupplierIdByName(Connection con, String supplierName) throws Exception {

        int supplierId = 0;

        PreparedStatement pst = con.prepareStatement(
                "SELECT supplier_id FROM Supplier WHERE supplier_name = ?"
        );
        pst.setString(1, supplierName);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            supplierId = rs.getInt("supplier_id");
        }

        rs.close();
        pst.close();

        return supplierId;
    }

   private Integer getFoodProductIdByIngredient(Connection con, String ingredient) throws Exception {
        PreparedStatement pst = con.prepareStatement(
                "SELECT FoodProduct_id FROM FoodProduct WHERE ingredients = ?"
        );
        pst.setString(1, ingredient);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            return rs.getInt("FoodProduct_id");
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Purches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Purches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Purches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Purches.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Purches().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
