/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package databasesystem_project;

import java.awt.Window;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Monster Huma H5 v4.1
 */
public class Remove_Employee extends javax.swing.JPanel {

    /**
     * Creates new form Remove_Employee_panel
     */
    public Remove_Employee() {
        initComponents();
        loadEmployeeList();
    }

    private void loadEmployeeList() {
        DefaultListModel<String> list_model = new DefaultListModel<>();

        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT emp_name FROM Employee WHERE role = 'Employee'";

            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("emp_name");
                list_model.addElement(name);
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            System.out.println("Hata (loadStockTable): " + e.getMessage());
        }

        list_of_employee.setModel(list_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_of_employee = new javax.swing.JList<>();
        bttn_remove_emp = new javax.swing.JButton();
        bttn_logout_re = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(460, 550));

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel1.setText("REMOVE EMPLOYEE");

        jScrollPane1.setViewportView(list_of_employee);

        bttn_remove_emp.setText("REMOVE");
        bttn_remove_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_remove_empActionPerformed(evt);
            }
        });

        bttn_logout_re.setText("Logout");
        bttn_logout_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_logout_reActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttn_logout_re)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(bttn_remove_emp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(bttn_remove_emp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(bttn_logout_re)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_logout_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_logout_reActionPerformed
        // TODO add your handling code here:
        Admin_Login admin_login = new Admin_Login();
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // Bulunduğu frame'i kapat
        }
        admin_login.setVisible(true);
    }//GEN-LAST:event_bttn_logout_reActionPerformed

    private void bttn_remove_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_remove_empActionPerformed
        // TODO add your handling code here:
        String selected_emp = list_of_employee.getSelectedValue();
        if (selected_emp == null) {
            JOptionPane.showMessageDialog(this, "Please select an employee!");
            return;
        }

        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {
                String sql = "DELETE FROM Employee WHERE emp_name = ? AND role = 'Employee'";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selected_emp);

                int rows = pst.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Employee removed successfully!");

                    // Listeden silinen ismi çıkar
                    loadEmployeeList();  // listeyi yenile
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to remove employee!");
                }

                pst.close();
                conn.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage() + "\n" + selected_emp);
            e.printStackTrace();
        }

    }//GEN-LAST:event_bttn_remove_empActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_logout_re;
    private javax.swing.JButton bttn_remove_emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_of_employee;
    // End of variables declaration//GEN-END:variables
}
