/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package databasesystem_project;

import java.awt.Window;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Monster Huma H5 v4.1
 */
public class Remove_Product extends javax.swing.JPanel {

    /**
     * Creates new form Remove_Product_panel
     */
    public Remove_Product() {
        initComponents();
        loadProductList();
    }
    
    private void loadProductList() {
        DefaultListModel<String> list_model = new DefaultListModel<>();

        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT product_name FROM Product";

            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String name = rs.getString("product_name");
                list_model.addElement(name);
            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            System.out.println("Hata (loadStockTable): " + e.getMessage());
        }

        list_product_to_remove.setModel(list_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttn_remove_rp = new javax.swing.JButton();
        bttn_logout_rp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_product_to_remove = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(460, 550));

        bttn_remove_rp.setText("REMOVE");
        bttn_remove_rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_remove_rpActionPerformed(evt);
            }
        });

        bttn_logout_rp.setText("Logout");
        bttn_logout_rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_logout_rpActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(list_product_to_remove);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel1.setText("REMOVE PRODUCT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttn_logout_rp)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttn_remove_rp)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(bttn_remove_rp)
                .addGap(41, 41, 41)
                .addComponent(bttn_logout_rp)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_logout_rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_logout_rpActionPerformed
        // TODO add your handling code here:
        Admin_Login admin_login = new Admin_Login();
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();   // Bulunduğu frame'i kapat
        }
        admin_login.setVisible(true);
    }//GEN-LAST:event_bttn_logout_rpActionPerformed

    private void bttn_remove_rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_remove_rpActionPerformed
        // TODO add your handling code here:
        String selected_pro = list_product_to_remove.getSelectedValue();
        if (selected_pro == null) {
            JOptionPane.showMessageDialog(this, "Please select an product!");
            return;
        }

        try {
            Connection conn = DBConnection.getConnection();
            if (conn != null) {
                String sql = "DELETE FROM Product WHERE product_name = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, selected_pro);

                int rows = pst.executeUpdate();

                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Product removed successfully!");

                    // Listeden silinen ismi çıkar
                    loadProductList();  // listeyi yenile
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to remove product!");
                }

                pst.close();
                conn.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage() + "\n" + selected_pro);
            e.printStackTrace();
        }
    }//GEN-LAST:event_bttn_remove_rpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_logout_rp;
    private javax.swing.JButton bttn_remove_rp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_product_to_remove;
    // End of variables declaration//GEN-END:variables
}
