/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databasesystem_project;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author imans
 */
public class Stock extends javax.swing.JFrame {

    String user_name;
    int quantity;
    ArrayList<AlertMessage> message_list = new ArrayList<>();

    /**
     * Creates new form Stock
     */
    public Stock(String name) {
        initComponents();
        this.user_name = name;
        loadStockTable();
        updateAlertButtonColor();
    }

    private void updateAlertButtonColor() {
        boolean hasUnseen = false;

        for (AlertMessage m : message_list) {
            if (m.seen == 0) {
                hasUnseen = true;
                break;
            }
        }

        if (hasUnseen) {
            bttn_alert.setBackground(Color.RED);
            bttn_alert.setOpaque(true);
            bttn_alert.setBorderPainted(false);
        } else {
            bttn_alert.setBackground(Color.WHITE);
        }
    }

    private void loadStockTable() {
        System.out.println("loadStockTable içine girdi");
        message_list.clear();
        try {
            Connection con = DBConnection.getConnection();

            String sql = "SELECT s.product_id, p.product_name, s.quantity "
                    + "FROM Stock s JOIN Product p ON s.product_id = p.product_id";

            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) loadStockTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                quantity = rs.getInt("quantity");
                int product_id = rs.getInt("product_id");
                String product_name = rs.getString("product_name");

                Object[] row = {product_id, product_name, quantity};
                model.addRow(row);
                checkMessage(quantity, product_id, product_name);
            }

            rs.close();
            pst.close();
            con.close();
            System.out.println("Toplam mesaj sayısı: " + message_list.size());

        } catch (Exception e) {
            System.out.println("Hata (loadStockTable): " + e.getMessage());
        }
    }

    private void checkMessage(int stock, int id, String name) {
        System.out.println("checkMessage içine girdi");
        String sql = "SELECT product_id, reorder_level FROM StockReorder WHERE product_id = ? AND reorder_level >= ?";
        try (Connection conn = DBConnection.getConnection(); PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, id);
            ps.setInt(2, stock);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int product_id = rs.getInt("product_id");
                int reorder_level = rs.getInt("reorder_level");
                System.out.println("\n\nstock: " + stock + "      reorder level:" + reorder_level);
                if (stock != 0) {
                    message_list.add(new AlertMessage("Low Stock", "The " + name + " is almost sold out. You need to reorder the stock.", product_id));
                    System.out.println("\naz stock mesajı eklendi: " + name);
                } else {
                    message_list.add(new AlertMessage("Out of Stock", "We've run out of " + name + ". You need to order again.", product_id));
                    System.out.println("stock bitti mesaajı eklendi: " + name);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loadStockTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bttn_menu = new javax.swing.JButton();
        bttn_alert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        loadStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product_id", "Product_name", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(loadStockTable);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jLabel1.setText("STOCK");

        bttn_menu.setText("Menu");
        bttn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_menuActionPerformed(evt);
            }
        });

        bttn_alert.setBackground(new java.awt.Color(204, 255, 255));
        bttn_alert.setIcon(new javax.swing.ImageIcon("C:\\Users\\imans\\OneDrive\\Masaüstü\\images (1)-Photoroom.png")); // NOI18N
        bttn_alert.setBorder(null);
        bttn_alert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_alertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttn_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(bttn_menu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttn_alert, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bttn_menu)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_menuActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(user_name);
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_bttn_menuActionPerformed

    private void bttn_alertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_alertActionPerformed
        // TODO add your handling code here:
        for (AlertMessage message : message_list) {
            if (message.seen == 0) {
                message.createMessage();
            }
        }

        updateAlertButtonColor();
    }//GEN-LAST:event_bttn_alertActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Stock().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_alert;
    private javax.swing.JButton bttn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loadStockTable;
    // End of variables declaration//GEN-END:variables
}
